name: solo_leveling
description: A new Flutter project.
publish_to: 'none'
version: 1.1.1+19

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.2.2
  confetti: ^0.7.0
  cupertino_icons: ^1.0.2
  image_picker: ^1.0.4
  intl: ^0.18.1
  provider: ^6.1.1
  table_calendar: ^3.0.9
  audioplayers: ^5.2.1
  flutter_native_splash: ^2.4.6
  animated_background: ^2.0.0
  lottie: 3.3.1
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true

  assets:
    - assets/solo_leveling_intro.png
    - assets/forest.png
    - assets/creacion.png
    - assets/avatars/mago/
    - assets/avatars/paladin/
    - assets/avatars/barbaro/
    - assets/avatars/nigromante/
    - assets/avatars/picaro/
    - assets/sounds/sword-tap.mp3
    - assets/animations/palimita.json
    - assets/animations/confeti.json
    - assets/moneda.png

  fonts:
    - family: OptimusPrinceps
      fonts:
        - asset: assets/fonts/OptimusPrinceps.ttf


