name: solo_leveling
description: A new Flutter project.
publish_to: 'none'
version: 1.1.1+9

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.2.2
  confetti: ^0.7.0
  cupertino_icons: ^1.0.2
  image_picker: ^1.0.4
  intl: ^0.18.1
  provider: ^6.1.1
  table_calendar: ^3.0.9
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_native_splash: ^2.3.1
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true

  assets:
    - assets/solo-leveling-intro.png
    - assets/icon_app.png
    - assets/forest.png
    - assets/creacion.png

  fonts:
    - family: OptimusPrinceps
      fonts:
        - asset: assets/fonts/OptimusPrinceps.ttf

flutter_launcher_icons:
  android: true
  ios: true
  image_path_android: "assets/icon_app.png"
  image_path_ios: "assets/icon_app.png"

flutter_native_splash:
  color: "#000000"
  fullscreen: true
